spring:
  # 应用程序名称
  application:
    name: SpringBoot-HouseMarket
  
  # 数据源配置
  datasource:
    # 数据库连接地址
    url: jdbc:mysql://localhost:3306/housemarket?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    # 数据库用户名
    username: root
    # 数据库密码
    password: root
    # JDBC驱动类名
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    # 是否显示SQL语句
    show-sql: true
    hibernate:
      # Hibernate的DDL策略
      ddl-auto: update
      naming:
        # 命名策略
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        # Hibernate方言
        dialect: org.hibernate.dialect.MySQLDialect